---
# NetApp Cluster System Setup
- hosts: localhost
  collections:
    - netapp.ontap
  gather_facts: false
  vars:
    login: &login
      hostname: "{{ hostname }}" # NetApp Cluster IP
      username: "{{ username }}" # Cluster User
      password: "{{ password }}" # Cluster Password
      https: true
      validate_certs: false
  vars_files:
    - var_dm1ncp6000.yml
  tasks:
    - name: Get list of nodes in the cluster
      na_ontap_rest_info:
        <<: *login
        gather_subset:
          - cluster/nodes
      register: node_list
      
    - name: set fact
      set_fact: old_names="{{ node_list['ontap_info']['cluster/nodes']['records'] }}"
                new_names="{{ node_names }}"

#    - name: print old names
#      debug: 
#        msg: "{{ old_names }}"

#    - name: print new names
#      debug: 
#        msg: "{{ new_names }}"
#      loop:
#      - "{{ node_list['ontap_info']['cluster/nodes']['records'], node_names }}"
#      - "{{ node_names }}"
      
    - name: Rename Nodes
      na_ontap_node:
        use_rest: never
        from_name: "{{ item.name }}"
        name: new_names
        <<: *login
      with_items:
      - "{{ old_names }}"