---
# NetApp ONTAP create SMB shares
- hosts: localhost
  collections:
    - netapp.ontap
  gather_facts: false
#  vars_prompt:
#    - name: username
#      prompt: enter the username
#      private: no
#    - name: password
#      prompt: enter password
  vars:
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
    drlogin: &drlogin
      hostname: "{{ drclustername }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  vars_files:
    - var_smb_file_shares.yml
  tasks:
    - name: Create SMB shares inc volume from application template
      na_ontap_volume:
        use_rest: always
        state: present
        name: "{{ item.volume }}"
        vserver: "{{ item.vserver }}"
        size: "{{ item.size }}"
        size_unit: "{{ item.size_unit }}"
        junction_path: "{{ '/' + item.volume }}"
        space_guarantee: none
        tiering_policy: auto
        volume_security_style: ntfs
        percent_snapshot_space: 20
        snapshot_policy: "{{ item.snap_policy }}"
        comment: "{{ item.comment }}"
        nas_application_template:
          cifs_access:
            - user_or_group: "Authenticated Users"
        <<: *login
      with_items: "{{ smb_file_shares }}"

    - name: 'get aggr info for dr cluster'
      na_ontap_rest_info:
        <<: *drlogin
        use_python_keys: true
        gather_subset:
          - storage/aggregates
        parameters:
          space.block_storage.physical_used_percent: "<85"
        fields:
          - 'name'
          - 'space.block_storage.available'
      register: dr_aggregate_info

    - name: 'create clean list of dicts from aggregate json'
      set_fact: 
        dr_aggregate_clean: "{{ dr_aggregate_info | json_query(query_dr_aggr_info) }}"
      vars:
        query_dr_aggr_info: "ontap_info.storage_aggregates.records[*].{ name: name, space_available: space.block_storage.available }"
    
    - name: 'sort the list by space_available'
      set_fact:
        dr_aggregate: "{{ dr_aggregate_clean | sort(attribute='space_available', reverse=true) }}"   

    - name: 'get svm peer info from cluster'
      na_ontap_rest_info:
        <<: *login
        use_python_keys: true
        gather_subset:
          - svm/peers
        parameters:
          svm: "{{ primary_svm }}"
        fields:
          - peer.svm
      register: svmpeer_info

    - name: 'create clean list of dicts from aggregate json'
      set_fact: 
        dr_svm: "{{ svmpeer_info | json_query(query_svmpeer_info) }}"
      vars:
        query_svmpeer_info: "ontap_info.svm_peers.records[*].{ name: name }"

    - name: Create snapmirror destination volumes
      when: item.replicated == 'yes'
      na_ontap_volume:
        use_rest: always
        state: present
        name: "{{ item.volume + '_mv1' }}"
        vserver: "{{ dr_svm[0].name }}"
        aggregate_name: "{{ dr_aggregate[0].name }}"
        size: "{{ item.size }}"
        size_unit: "{{ item.size_unit }}"
        type: dp
        space_guarantee: none
        tiering_policy: all
        comment: "{{ item.comment }}" + "DR and Intellisnap DP volume"
        <<: *login
      with_items: "{{ smb_file_shares }}"

    - name: Create and initialise SnapMirror relationships
      when: item.replicated == 'yes'
      na_ontap_snapmirror:
        use_rest: always
        state: present
        policy: MirrorAndVault
        initialize: true
        source_endpoint:
          cluster: "{{ clustername }}"
          path: "{{ item.vserver + ':' + item.volume }}"
        destination_endpoint:
           cluster: "{{ drclustername }}"
           path: "{{ dr_svm[0].name + ':' + item.volume + '_mv1' }}"
        schedule: "{{ item.schedule }}"
        <<: *login
      with_items: "{{ smb_file_shares }}"

    - name: Create snapmirror destination volumes
      when: item.replicated == 'no'
      na_ontap_volume:
        use_rest: always
        state: present
        name: "{{ item.volume + '_v1' }}"
        vserver: "{{ dr_svm[0].name }}"
        aggregate_name: "{{ dr_aggregate[0].name }}"
        size: "{{ item.size }}"
        size_unit: "{{ item.size_unit }}"
        type: dp
        space_guarantee: none
        tiering_policy: all
        comment: "{{ item.comment }}" + "Intellisnap DP volume"
        <<: *login
      with_items: "{{ smb_file_shares }}"

    - name: Create and initialise SnapMirror relationships
      when: item.replicated == 'no'
      na_ontap_snapmirror:
        use_rest: always
        state: present
        policy: MirrorAndVault
        initialize: true
        source_endpoint:
          cluster: "{{ clustername }}"
          path: "{{ item.vserver + ':' + item.volume }}"
        destination_endpoint:
           cluster: "{{ drclustername }}"
           path: "{{ dr_svm[0].name + ':' + item.volume + '_v1' }}"
        schedule: "{{ item.schedule }}"
        <<: *login
      with_items: "{{ smb_file_shares }}"

    - name: mount destination volumes for access
      when: item.dest_vserver is defined
      na_ontap_volume:
        use_rest: always
        state: present
        name: "{{ item.volume + '_dest' }}"
        vserver: "{{ item.dest_vserver }}"
        junction_path: "{{ '/' + item.volume + '_dest' }}"
        <<: *login
      with_items: "{{ smb_file_shares }}"

    - name: create SMB shares for mirrored volumes
      when: item.dest_vserver is defined
      na_ontap_cifs:
        use_rest: always
        state: present
        share_name: "{{ item.volume }}"
        vserver: "{{ item.dest_vserver }}"
        path: "{{ '/' + item.volume + '_dest' }}"
        show_snapshot: true
        <<: *login
      with_items: "{{ smb_file_shares }}"

    - name: configure SMB permissions
      when: item.dest_vserver is defined
      na_ontap_cifs_acl:
        use_rest: always
        state: present
        share_name: "{{ item.volume }}"
        vserver: "{{ item.dest_vserver }}"
        user_or_group: "Authenticated Users"
        permission: "full_control"
        <<: *login
      with_items: "{{ smb_file_shares }}"

    - name: remove everyone permission
      when: item.dest_vserver is defined
      na_ontap_cifs_acl:
        use_rest: always
        state: absent
        share_name: "{{ item.volume }}"
        vserver: "{{ item.dest_vserver }}"
        user_or_group: "Everyone"
        <<: *login
      with_items: "{{ smb_file_shares }}"